/**
 * created by rpal
 */

export const SECTION_EVENTS = {
    SECTION_INIT: "SECTION_INIT",
    SECTION_LOAD_INPROGRESS: "SECTION_LOAD_INPROGRESS",
    SECTION_LOAD_SUCCESS: "SECTION_LOAD_SUCCESS",
    SECTION_UNLOAD: "SECTION_UNLOADED",
    SECTION_REFRESH: "SECTION_REFRESH",
    SECTION_LOAD_TIMEOUT: "SECTION_LOAD_TIMEOUT",
    SECTION_LOAD_FAILED: "SECTION_LOAD_FAILED",
    WIDGET_INITIALIZED: "WIDGET_INITIALIZED",
    WIDGET_RENDERED: "WIDGET_RENDERED",
    WIDGET_LOADED: "WIDGET_LOADED"
}
