export const operatorMap = {

    "STRING": [

        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "DOES_NOT_CONTAINS", "label": "360.admin.operatorMap.not_contain", "default": false},
        { "value": "CONTAINS", "label": "360.admin.operatorMap.contains", "default": false},
        { "value": "STARTS_WITH", "label": "360.admin.operatorMap.starts_with", "default": true},
        { "value": "ENDS_WITH", "label": "360.admin.operatorMap.ends_with", "default": false},
        { "value": "IN", "label": "360.admin.operatorMap.in", "default": false},
        { "value": "NOT_IN", "label": "360.admin.operatorMap.not_in", "default": false}
    ],
    GSID: [
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": true},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "IN", "label": "360.admin.operatorMap.in", "default": false},
        { "value": "NOT_IN", "label": "360.admin.operatorMap.not_in", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false}
    ],
    "SFDCID": [

        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "DOES_NOT_CONTAINS", "label": "360.admin.operatorMap.not_contain", "default": false},
        { "value": "CONTAINS", "label": "360.admin.operatorMap.contains", "default": false},
        { "value": "STARTS_WITH", "label": "360.admin.operatorMap.starts_with", "default": true},
        { "value": "ENDS_WITH", "label": "360.admin.operatorMap.ends_with", "default": false},
    ],
    "URL": [

        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "DOES_NOT_CONTAINS", "label": "360.admin.operatorMap.not_contain", "default": false},
        { "value": "CONTAINS", "label": "360.admin.operatorMap.contains", "default": false},
        { "value": "STARTS_WITH", "label": "360.admin.operatorMap.starts_with", "default": true},
        { "value": "ENDS_WITH", "label": "360.admin.operatorMap.ends_with", "default": false},
    ],
    "EMAIL": [

        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": true},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "DOES_NOT_CONTAINS", "label": "360.admin.operatorMap.not_contain", "default": false},
        { "value": "CONTAINS", "label": "360.admin.operatorMap.contains", "default": false},
        { "value": "STARTS_WITH", "label": "360.admin.operatorMap.starts_with", "default": false},
        { "value": "ENDS_WITH", "label": "360.admin.operatorMap.ends_with", "default": false},
        { "value": "IN", "label": "360.admin.operatorMap.in", "default": false},
        { "value": "NOT_IN", "label": "360.admin.operatorMap.not_in", "default": false}
    ],
    "TEXT": [

        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "DOES_NOT_CONTAINS", "label": "360.admin.operatorMap.not_contain", "default": false},
        { "value": "CONTAINS", "label": "360.admin.operatorMap.contains", "default": false},
        { "value": "STARTS_WITH", "label": "360.admin.operatorMap.starts_with", "default": true},
        { "value": "ENDS_WITH", "label": "360.admin.operatorMap.ends_with", "default": false},
        { "value": "IN", "label": "360.admin.operatorMap.in", "default": false},
        { "value": "NOT_IN", "label": "360.admin.operatorMap.not_in", "default": false}
    ],
    "PHONE": [
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": true},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "DOES_NOT_CONTAINS", "label": "360.admin.operatorMap.not_contain", "default": false},
        { "value": "CONTAINS", "label": "360.admin.operatorMap.contains", "default": false},
        { "value": "STARTS_WITH", "label": "360.admin.operatorMap.starts_with", "default": false},
        { "value": "ENDS_WITH", "label": "360.admin.operatorMap.ends_with", "default": false},
    ],
    "BOOLEAN": [
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": true},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
    ],
    "DATE": [
        { "value": "GTE", "label": "360.admin.operatorMap.greater_equal", "default": true},
        { "value": "LTE", "label": "360.admin.operatorMap.less_equal", "default": false},
        { "value": "LT", "label": "360.admin.operatorMap.less_than", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "GT", "label": "360.admin.operatorMap.greater_than", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "BTW", "label": "360.admin.operatorMap.between", "default": false},
    ],
    "DATETIME": [
        { "value": "GTE", "label": "360.admin.operatorMap.greater_equal", "default": true},
        { "value": "LTE", "label": "360.admin.operatorMap.less_equal", "default": false},
        { "value": "LT", "label": "360.admin.operatorMap.less_than", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "GT", "label": "360.admin.operatorMap.greater_than", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "BTW", "label": "360.admin.operatorMap.between", "default": false},
    ],
    "MULTIPICKLIST": [
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "IN", "label": "360.admin.operatorMap.in", "default": true},
        { "value": "NOT_IN", "label": "360.admin.operatorMap.not_in", "default": false},
    ],
    "MULTISELECTDROPDOWNLIST": [
        // { "value": "IS_NULL", "label": "is null"},
        // { "value": "IS_NOT_NULL", "label": "is not null"},
        { "value": "IN", "label": "360.admin.operatorMap.in", "default": true},
        { "value": "NOT_IN", "label": "360.admin.operatorMap.not_in", "default": false},
    ],
    "PICKLIST": [
        /*{ "value": "EQ", "label": "equals"},
        { "value": "NE", "label": "not equal to"},*/
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        /*{ "value": "DOES_NOT_CONTAINS", "label": "does not contain"},
        { "value": "CONTAINS", "label": "contains"},
        { "value": "STARTS_WITH", "label": "starts with"},
        { "value": "ENDS_WITH", "label": "ends with"},*/
        { "value": "IN", "label": "360.admin.operatorMap.in", "default": true},
        { "value": "NOT_IN", "label": "360.admin.operatorMap.not_in", "default": false},
    ],
    "INTEGER": [
        { "value": "GTE", "label": "360.admin.operatorMap.greater_equal", "default": true},
        { "value": "LTE", "label": "360.admin.operatorMap.less_equal", "default": false},
        { "value": "LT", "label": "360.admin.operatorMap.less_than", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "GT", "label": "360.admin.operatorMap.greater_than", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "BTW", "label": "360.admin.operatorMap.between", "default": false},
    ],
    "CURRENCY": [
        { "value": "GTE", "label": "360.admin.operatorMap.greater_equal", "default": true},
        { "value": "LTE", "label": "360.admin.operatorMap.less_equal", "default": false},
        { "value": "LT", "label": "360.admin.operatorMap.less_than", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "GT", "label": "360.admin.operatorMap.greater_than", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "BTW", "label": "360.admin.operatorMap.between", "default": false},
    ],
    "DOUBLE": [
        { "value": "GTE", "label": "360.admin.operatorMap.greater_equal", "default": true},
        { "value": "LTE", "label": "360.admin.operatorMap.less_equal", "default": false},
        { "value": "LT", "label": "360.admin.operatorMap.less_than", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "GT", "label": "360.admin.operatorMap.greater_than", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "BTW", "label": "360.admin.operatorMap.between", "default": false},
    ],
    "PERCENT": [
        { "value": "GTE", "label": "360.admin.operatorMap.greater_equal", "default": true},
        { "value": "LTE", "label": "360.admin.operatorMap.less_equal", "default": false},
        { "value": "LT", "label": "360.admin.operatorMap.less_than", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "GT", "label": "360.admin.operatorMap.greater_than", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "BTW", "label": "360.admin.operatorMap.between", "default": false},
    ],
    "PERCENTAGE": [
        { "value": "GTE", "label": "360.admin.operatorMap.greater_equal", "default": true},
        { "value": "LTE", "label": "360.admin.operatorMap.less_equal", "default": false},
        { "value": "LT", "label": "360.admin.operatorMap.less_than", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "GT", "label": "360.admin.operatorMap.greater_than", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "BTW", "label": "360.admin.operatorMap.between", "default": false},
    ],
    "NUMBER": [
        { "value": "GTE", "label": "360.admin.operatorMap.greater_equal", "default": true},
        { "value": "LTE", "label": "360.admin.operatorMap.less_equal", "default": false},
        { "value": "LT", "label": "360.admin.operatorMap.less_than", "default": false},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": false},
        { "value": "GT", "label": "360.admin.operatorMap.greater_than", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "BTW", "label": "360.admin.operatorMap.between", "default": false}
    ],
    "LOOKUP": [
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": true},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false},
        { "value": "IS_NULL", "label": "360.admin.operatorMap.is_null", "default": false},
        { "value": "IS_NOT_NULL", "label": "360.admin.operatorMap.not_null", "default": false},
        { "value": "IN", "label": "360.admin.operatorMap.in", "default": false},
        { "value": "NOT_IN", "label": "360.admin.operatorMap.not_in", "default": false},
    ],
    "FIELD": [
        { "value": "EQ", "label": "360.admin.operatorMap.equals", "default": true},
        { "value": "NE", "label": "360.admin.operatorMap.not_equal", "default": false}/* ,
        { "value": "IS_NULL", "label": "is null"},
        { "value": "IS_NOT_NULL", "label": "is not null"} */
    ],
};
