export const CHART_ATTRIBUTES = {
  index: 0,
  nodeHeight: 200,
  nodeWidth: 220,
  nodePadding: 15,
  imageCircleRadius: 20,
  nameFontSize: 14,
  nameHeight: 12,
  imageInitialsFontSize: 18,
  primaryInfoFontSize: 12,
  primaryInfoHeight: 14,
  secondaryInfoFontSize: 12,
  secondaryInfoHeight: 14,
  otherInfoFontSize: 12,
  otherInfoHeight: 14,
  peopleInfoFontSize: 12,
  peopleInfoHeight: 14,
  npsWidth: 81,
  npsHeight: 18,
  npsScoreHeight: 11,
  npsScoreFontSize: 10,
  lastEngagementFontSize: 11,
  lastEngagementHeight: 13,
  countWidth: 48,
  countHeight: 24,
  countFontHeight:15,
  countFontSize: '13px',
  collapseCircleRadius: 9,
  duration: 750,
  rootNodeTopMargin: 20,
  minMaxZoomProportions: [0.5, 1.0],
  initialZoomScale: 1,// 0.7
  linkLineSize: 220,
  collapsibleFontSize: '11px',
  nodeStroke: "#D9e0e9",
  nodeStrokeWidth: '1px',
  levelSeparation: 100,
  mixedHierarchyNodesSeparation: 15,
  rippleColor:"#3C94E7",
  rippleRadius:5,
  scaleFactor:1.20,
  scaleMin:0.5,
  scaleMax:1.0,
};