export enum IPaginatorAction {
  PREVIOUS_PAGE = 'PREVIOUS_PAGE',
  NEXT_PAGE = 'NEXT_PAGE',
  PAGE_CHANGE = 'PAGE_CHANGE',
  PAGESIZE_CHANGE = 'PAGESIZE_CHANGE',
  FETCH_NEXT_PAGE = 'FETCH_NEXT_PAGE',
  FETCH_PREVIOUS_PAGE = 'FETCH_PREVIOUS_PAGE'
}
